version: '3.5'

services:
  php:
    image: php_hello_img:latest 
    container_name: php_hello_container
    build: .
    ports:
      - 8085:80
    volumes:
      - ./:/var/www/html/
    restart: always